package com.campus.secondhand.trading;

import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import java.math.BigDecimal;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;

class TradingWorkflowTest{
 private final TradeOrderRepository orders=mock(TradeOrderRepository.class);private final AccountPort accounts=mock(AccountPort.class);private final MarketplacePort marketplace=mock(MarketplacePort.class);private final TradingEventStore events=mock(TradingEventStore.class);private final InboxEventRepository inbox=mock(InboxEventRepository.class);private final Clock clock=Clock.fixed(Instant.parse("2026-08-28T02:00:00Z"),ZoneOffset.UTC);private final TradingProperties props=new TradingProperties("a","m","token","jwt",1440,4320,false,300,800);private TradingWorkflowService workflow;
 @BeforeEach void setup(){workflow=new TradingWorkflowService(orders,accounts,marketplace,events,inbox,clock,props);}
 @Test void purchaseIntentKeepsProductPublicAndStoresSnapshots(){CurrentActor actor=new CurrentActor(2,"STUDENT",0);when(accounts.requireActiveStudent(2)).thenReturn(account(2,"买家"));when(accounts.requireActiveStudent(7)).thenReturn(account(7,"卖家"));when(marketplace.require(10)).thenReturn(item());when(orders.findFirstByItemIdAndBuyerIdAndStatusIn(eq(10L),eq(2L),anyList())).thenReturn(Optional.empty());when(orders.saveAndFlush(any())).thenAnswer(call->{TradeOrder order=call.getArgument(0);order.setId(100L);return order;});var result=workflow.requestPurchase(actor,10);assertThat(result.status()).isEqualTo(OrderStatus.PURCHASE_REQUESTED);assertThat(result.sellerNickname()).isEqualTo("卖家");verify(events,never()).append(anyString(),anyLong(),anyLong());}
 @Test void dependencyFailureCannotLeaveHalfOrder(){CurrentActor actor=new CurrentActor(2,"STUDENT",0);when(accounts.requireActiveStudent(2)).thenReturn(account(2,"买家"));when(marketplace.require(10)).thenThrow(TradingException.productUnavailable());assertThatThrownBy(()->workflow.requestPurchase(actor,10)).isInstanceOf(TradingException.class);verify(orders,never()).saveAndFlush(any());verify(events,never()).append(anyString(),anyLong(),anyLong());}
 @Test void sellerAcceptWritesOutboxBeforeFinalReservation(){TradeOrder order=order(OrderStatus.PURCHASE_REQUESTED);when(accounts.requireActiveStudent(7)).thenReturn(account(7,"卖家"));when(orders.findLockedById(100L)).thenReturn(Optional.of(order));when(marketplace.require(10)).thenReturn(item());when(orders.existsByItemIdAndSagaState(10L,SagaState.RESERVE_PENDING)).thenReturn(false);workflow.perform(new CurrentActor(7,"STUDENT",0),100,OrderAction.ACCEPT);assertThat(order.getSagaState()).isEqualTo(SagaState.RESERVE_PENDING);assertThat(order.getStatus()).isEqualTo(OrderStatus.PURCHASE_REQUESTED);verify(events).append("ItemReservationRequested",100,10);}
 @Test void strangerCannotOperateOrder(){TradeOrder order=order(OrderStatus.PURCHASE_REQUESTED);when(accounts.requireActiveStudent(9)).thenReturn(account(9,"陌生人"));when(orders.findLockedById(100L)).thenReturn(Optional.of(order));assertThatThrownBy(()->workflow.perform(new CurrentActor(9,"STUDENT",0),100,OrderAction.CANCEL)).isInstanceOf(TradingException.class).hasMessageContaining("不能查看");}
 @Test void marketplaceResultIsIdempotentAndClosesOtherIntent(){TradeOrder accepted=order(OrderStatus.PURCHASE_REQUESTED);accepted.setSagaState(SagaState.RESERVE_PENDING);TradeOrder other=order(OrderStatus.PURCHASE_REQUESTED);other.setId(101L);other.setBuyerId(3L);when(orders.findLockedById(100L)).thenReturn(Optional.of(accepted));when(orders.findByItemIdAndStatus(10L,OrderStatus.PURCHASE_REQUESTED)).thenReturn(List.of(accepted,other));when(inbox.existsById("e1")).thenReturn(false,true);var event=new TradingWorkflow.MarketplaceResult("e1","ItemReserved",100,10,null);workflow.applyMarketplaceResult(event);workflow.applyMarketplaceResult(event);assertThat(accepted.getStatus()).isEqualTo(OrderStatus.WAITING_HANDOVER);assertThat(other.getStatus()).isEqualTo(OrderStatus.DECLINED);verify(inbox,times(1)).save(any());}
 @Test void expiredReservationRequestsReleaseInsteadOfClosingLocally(){TradeOrder order=order(OrderStatus.WAITING_HANDOVER);order.setExpiresAt(LocalDateTime.now(clock).minusSeconds(1));when(orders.findLockedById(100L)).thenReturn(Optional.of(order));assertThat(workflow.expire(100)).isTrue();assertThat(order.getSagaState()).isEqualTo(SagaState.RELEASE_PENDING);assertThat(order.getStatus()).isEqualTo(OrderStatus.WAITING_HANDOVER);verify(events).append("ItemReleaseRequested",100,10);}
 @Test void pendingSagaIsNotOverwrittenByGenericExpiry(){TradeOrder order=order(OrderStatus.PURCHASE_REQUESTED);order.setSagaState(SagaState.RESERVE_PENDING);order.setExpiresAt(LocalDateTime.now(clock).minusSeconds(1));when(orders.findLockedById(100L)).thenReturn(Optional.of(order));assertThat(workflow.expire(100)).isFalse();assertThat(order.getStatus()).isEqualTo(OrderStatus.PURCHASE_REQUESTED);assertThat(order.getSagaState()).isEqualTo(SagaState.RESERVE_PENDING);verifyNoInteractions(events);}
 private AccountPort.AccountSnapshot account(long id,String name){return new AccountPort.AccountSnapshot(id,"u"+id,name,"学院路",100,"ACTIVE","STUDENT",LocalDateTime.now(clock));}
 private MarketplacePort.ItemSnapshot item(){return new MarketplacePort.ItemSnapshot(10,7,"教材",new BigDecimal("20.00"),"/image.jpg","ON_SALE","VISIBLE");}
 private TradeOrder order(OrderStatus status){TradeOrder o=new TradeOrder();o.setId(100L);o.setItemId(10L);o.setBuyerId(2L);o.setSellerId(7L);o.setItemTitle("教材");o.setItemPrice(new BigDecimal("20"));o.setBuyerNickname("买家");o.setSellerNickname("卖家");o.setStatus(status);o.setExpiresAt(LocalDateTime.now(clock).plusHours(1));o.setCreatedAt(LocalDateTime.now(clock));o.setUpdatedAt(LocalDateTime.now(clock));return o;}
}
