package com.campus.secondhand.trading;

import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.campus.secondhand.trading.chat.DirectChat;import java.math.BigDecimal;import java.time.*;import java.util.*;import javax.crypto.spec.SecretKeySpec;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.security.oauth2.jose.jws.MacAlgorithm;import org.springframework.security.oauth2.jwt.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class TradingApiTest{
 private static final String SECRET="test-internal-jwt-secret-at-least-32-bytes";@Autowired MockMvc mvc;@Autowired TradingEventStore eventStore;@Autowired OutboxEventRepository outbox;@MockitoBean TradingWorkflow trading;@MockitoBean DirectChat chat;
 @Test void protectedRoutesRejectAnonymous()throws Exception{
  mvc.perform(get("/api/orders")).andExpect(status().isUnauthorized()); mvc.perform(get("/api/orders/desk")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/orders").contentType(MediaType.APPLICATION_JSON).content("{\"itemId\":10}")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/orders/100/actions").contentType(MediaType.APPLICATION_JSON).content("{\"action\":\"ACCEPT\"}")).andExpect(status().isUnauthorized());
  mvc.perform(post("/api/chat/conversations").contentType(MediaType.APPLICATION_JSON).content("{\"itemId\":10}")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/chat/order-conversations").contentType(MediaType.APPLICATION_JSON).content("{\"orderId\":100}")).andExpect(status().isUnauthorized()); mvc.perform(get("/api/chat/conversations")).andExpect(status().isUnauthorized()); mvc.perform(get("/api/chat/conversations/c1/messages")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/chat/conversations/c1/messages").contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"hi\"}")).andExpect(status().isUnauthorized()); mvc.perform(post("/api/chat/conversations/c1/read").contentType(MediaType.APPLICATION_JSON).content("{\"throughSequence\":1}")).andExpect(status().isUnauthorized()); mvc.perform(put("/api/chat/blocks/7")).andExpect(status().isUnauthorized()); mvc.perform(delete("/api/chat/blocks/7")).andExpect(status().isUnauthorized()); mvc.perform(get("/api/chat/unread-count")).andExpect(status().isUnauthorized());
 }
 @Test void orderIdentityAlwaysComesFromGatewayJwt()throws Exception{when(trading.requestPurchase(any(),eq(10L))).thenReturn(view());mvc.perform(post("/api/orders").header("Authorization","Bearer "+jwt(2,"STUDENT")).contentType(MediaType.APPLICATION_JSON).content("{\"itemId\":10,\"buyerId\":999}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.buyerId").value(2));verify(trading).requestPurchase(argThat(actor->actor.userId()==2),eq(10L));}
 @Test void internalInquiryRequiresServiceToken()throws Exception{when(trading.activeInquiry(10,2)).thenReturn(Optional.of(view()));mvc.perform(get("/internal/trading/items/10/buyers/2/active-inquiry")).andExpect(status().isUnauthorized());mvc.perform(get("/internal/trading/items/10/buyers/2/active-inquiry").header("X-Internal-Service-Token","test-internal-service-token-32-bytes")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("PURCHASE_REQUESTED"));}
 @Test void commandIsDurablyStoredBeforeRabbitDelivery(){outbox.deleteAll();eventStore.append("ItemReservationRequested",100,10);assertThat(outbox.findAll()).singleElement().satisfies(event->{assertThat(event.getEventType()).isEqualTo("ItemReservationRequested");assertThat(event.getPublishedAt()).isNull();});}
 @Test void orderListDeskAndActionExposeSuccessAndValidateInput()throws Exception{
  when(trading.list(any())).thenReturn(List.of(view()));
  when(trading.browse(any(),eq(TradingWorkflow.Perspective.SELLING),eq(TradingWorkflow.Stage.REQUESTS))).thenReturn(new TradingWorkflow.Desk(TradingWorkflow.Perspective.SELLING,TradingWorkflow.Stage.REQUESTS,new TradingWorkflow.Summary(1,0,0,1),List.of()));
  when(trading.perform(any(),eq(100L),eq(OrderAction.ACCEPT))).thenReturn(view());
  String auth="Bearer "+jwt(7,"STUDENT");
  mvc.perform(get("/api/orders").header("Authorization",auth)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)).andExpect(jsonPath("$.data[0].id").value(100));
  mvc.perform(get("/api/orders/desk").header("Authorization",auth).queryParam("perspective","SELLING").queryParam("stage","REQUESTS")).andExpect(status().isOk()).andExpect(jsonPath("$.data.perspective").value("SELLING")).andExpect(jsonPath("$.data.summary.actionable").value(1));
  mvc.perform(post("/api/orders/100/actions").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"action\":\"ACCEPT\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.id").value(100));
  mvc.perform(post("/api/orders").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false)).andExpect(jsonPath("$.message").value(org.hamcrest.Matchers.containsString("itemId")));
  verify(trading).list(argThat(a->a.userId()==7)); verify(trading).browse(argThat(a->a.userId()==7),eq(TradingWorkflow.Perspective.SELLING),eq(TradingWorkflow.Stage.REQUESTS)); verify(trading).perform(argThat(a->a.userId()==7),eq(100L),eq(OrderAction.ACCEPT));
 }
 @Test void chatEndpointsReturnDataAndUseAuthenticatedActor()throws Exception{
  var conversation=new DirectChat.ConversationView("c1",10L,"教材",null,7L,"卖家","你好",LocalDateTime.now(),2,1,false,false);
  var message=new DirectChat.MessageView(2L,2L,"可以面交",LocalDateTime.now());
  when(chat.open(2L,10L)).thenReturn(conversation); when(chat.openTrade(2L,100L)).thenReturn(conversation); when(chat.conversations(2L,0,30)).thenReturn(new DirectChat.ConversationPage(List.of(conversation),0,30,false,1)); when(chat.history(2L,"c1",null,50)).thenReturn(new DirectChat.MessagePage(conversation,List.of(message),null,false)); when(chat.send(2L,"c1","可以面交")).thenReturn(message); when(chat.markRead(2L,"c1",2L)).thenReturn(conversation); when(chat.unreadTotal(2L)).thenReturn(1L);
  String auth="Bearer "+jwt(2,"STUDENT");
  mvc.perform(post("/api/chat/conversations").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"itemId\":10}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.id").value("c1"));
  mvc.perform(post("/api/chat/order-conversations").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"orderId\":100}")).andExpect(status().isOk());
  mvc.perform(get("/api/chat/conversations").header("Authorization",auth)).andExpect(status().isOk()).andExpect(jsonPath("$.data.totalUnread").value(1));
  mvc.perform(get("/api/chat/conversations/c1/messages").header("Authorization",auth)).andExpect(status().isOk()).andExpect(jsonPath("$.data.messages[0].body").value("可以面交"));
  mvc.perform(post("/api/chat/conversations/c1/messages").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"可以面交\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.senderId").value(2));
  mvc.perform(post("/api/chat/conversations/c1/read").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"throughSequence\":2}")).andExpect(status().isOk());
  mvc.perform(get("/api/chat/unread-count").header("Authorization",auth)).andExpect(status().isOk()).andExpect(jsonPath("$.data.count").value(1));
  mvc.perform(put("/api/chat/blocks/7").header("Authorization",auth)).andExpect(status().isOk()).andExpect(jsonPath("$.success").value(true)); mvc.perform(delete("/api/chat/blocks/7").header("Authorization",auth)).andExpect(status().isOk());
  mvc.perform(post("/api/chat/conversations/c1/messages").header("Authorization",auth).contentType(MediaType.APPLICATION_JSON).content("{\"body\":\"\"}")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.success").value(false));
  verify(chat).open(2L,10L); verify(chat).openTrade(2L,100L); verify(chat).send(2L,"c1","可以面交"); verify(chat).markRead(2L,"c1",2L); verify(chat).block(2L,7L); verify(chat).unblock(2L,7L);
 }
 private TradingWorkflow.OrderView view(){return new TradingWorkflow.OrderView(100,10,"教材",new BigDecimal("20"),2,"买家",7,"卖家",OrderStatus.PURCHASE_REQUESTED,LocalDateTime.of(2026,8,29,10,0),null,LocalDateTime.of(2026,8,28,10,0),List.of(OrderAction.CANCEL));}
 private String jwt(long user,String role){Instant now=Instant.now();JwtClaimsSet claims=JwtClaimsSet.builder().issuer("campus-gateway").subject(String.valueOf(user)).claim("role",role).claim("auth_version",1).issuedAt(now).expiresAt(now.plusSeconds(60)).build();JwtEncoder encoder=NimbusJwtEncoder.withSecretKey(new SecretKeySpec(SECRET.getBytes(java.nio.charset.StandardCharsets.UTF_8),"HmacSHA256")).build();return encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),claims)).getTokenValue();}
}
