package com.campus.secondhand.trading;

import static org.assertj.core.api.Assertions.assertThat;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.campus.secondhand.trading.chat.DirectChat;import java.math.BigDecimal;import java.time.*;import java.util.*;import javax.crypto.spec.SecretKeySpec;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.security.oauth2.jose.jws.MacAlgorithm;import org.springframework.security.oauth2.jwt.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class TradingApiTest{
 private static final String SECRET="test-internal-jwt-secret-at-least-32-bytes";@Autowired MockMvc mvc;@Autowired TradingEventStore eventStore;@Autowired OutboxEventRepository outbox;@MockitoBean TradingWorkflow trading;@MockitoBean DirectChat chat;
 @Test void protectedRoutesRejectAnonymous()throws Exception{mvc.perform(get("/api/orders")).andExpect(status().isUnauthorized());mvc.perform(get("/api/chat/unread-count")).andExpect(status().isUnauthorized());}
 @Test void orderIdentityAlwaysComesFromGatewayJwt()throws Exception{when(trading.requestPurchase(any(),eq(10L))).thenReturn(view());mvc.perform(post("/api/orders").header("Authorization","Bearer "+jwt(2,"STUDENT")).contentType(MediaType.APPLICATION_JSON).content("{\"itemId\":10,\"buyerId\":999}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.buyerId").value(2));verify(trading).requestPurchase(argThat(actor->actor.userId()==2),eq(10L));}
 @Test void internalInquiryRequiresServiceToken()throws Exception{when(trading.activeInquiry(10,2)).thenReturn(Optional.of(view()));mvc.perform(get("/internal/trading/items/10/buyers/2/active-inquiry")).andExpect(status().isUnauthorized());mvc.perform(get("/internal/trading/items/10/buyers/2/active-inquiry").header("X-Internal-Service-Token","test-internal-service-token-32-bytes")).andExpect(status().isOk()).andExpect(jsonPath("$.data.status").value("PURCHASE_REQUESTED"));}
 @Test void commandIsDurablyStoredBeforeRabbitDelivery(){outbox.deleteAll();eventStore.append("ItemReservationRequested",100,10);assertThat(outbox.findAll()).singleElement().satisfies(event->{assertThat(event.getEventType()).isEqualTo("ItemReservationRequested");assertThat(event.getPublishedAt()).isNull();});outbox.deleteAll();}
 private TradingWorkflow.OrderView view(){return new TradingWorkflow.OrderView(100,10,"教材",new BigDecimal("20"),2,"买家",7,"卖家",OrderStatus.PURCHASE_REQUESTED,LocalDateTime.of(2026,8,29,10,0),null,LocalDateTime.of(2026,8,28,10,0),List.of(OrderAction.CANCEL));}
 private String jwt(long user,String role){Instant now=Instant.now();JwtClaimsSet claims=JwtClaimsSet.builder().issuer("campus-gateway").subject(String.valueOf(user)).claim("role",role).claim("auth_version",1).issuedAt(now).expiresAt(now.plusSeconds(60)).build();JwtEncoder encoder=NimbusJwtEncoder.withSecretKey(new SecretKeySpec(SECRET.getBytes(java.nio.charset.StandardCharsets.UTF_8),"HmacSHA256")).build();return encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),claims)).getTokenValue();}
}
