package com.campus.secondhand.governance;

import static org.assertj.core.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;

class ContentGovernanceServiceTest {
    private final ContentReportRepository reports=mock(ContentReportRepository.class);private final ReportActionRepository actions=mock(ReportActionRepository.class);private final GovernanceInboxRepository inbox=mock(GovernanceInboxRepository.class);private final AccountGovernancePort accounts=mock(AccountGovernancePort.class);private final ReportTargetPort targets=mock(ReportTargetPort.class);private final GovernanceEventStore events=mock(GovernanceEventStore.class);private final Clock clock=Clock.fixed(Instant.parse("2026-08-28T03:00:00Z"),ZoneOffset.UTC);private ContentGovernanceService governance;
    @BeforeEach void setup(){governance=new ContentGovernanceService(reports,actions,inbox,accounts,targets,events,clock);}

    @Test void submitStoresOwnedSnapshotAndNoRemoteEntity(){when(accounts.requireActiveStudent(2)).thenReturn(account(2,"STUDENT"));when(targets.resolve(ReportTargetType.ITEM,10)).thenReturn(new ReportTargetPort.TargetSnapshot(10,7,"教材",ReportTargetType.ITEM,true));when(reports.saveAndFlush(any())).thenAnswer(call->{ContentReport r=call.getArgument(0);r.setId(100L);return r;});var view=governance.submit(new CurrentActor(2,"STUDENT"),new ContentGovernance.ReportDraft(ReportTargetType.ITEM,10L,ReportReason.FRAUD,"这是足够详细的举报说明文字"));assertThat(view.reporterId()).isEqualTo(2);assertThat(view.targetSummary()).isEqualTo("教材");assertThat(view.status()).isEqualTo(ReportStatus.OPEN);}
    @Test void reporterCannotReportOwnContent(){when(accounts.requireActiveStudent(2)).thenReturn(account(2,"STUDENT"));when(targets.resolve(ReportTargetType.ITEM,10)).thenReturn(new ReportTargetPort.TargetSnapshot(10,2,"自己的商品",ReportTargetType.ITEM,true));assertThatThrownBy(()->governance.submit(new CurrentActor(2,"STUDENT"),new ContentGovernance.ReportDraft(ReportTargetType.ITEM,10L,ReportReason.SPAM,"这是足够详细的举报说明文字"))).isInstanceOf(GovernanceException.class);verify(reports,never()).saveAndFlush(any());}
    @Test void resolvedDecisionWritesPendingOutboxInsteadOfPretendingApplied(){ContentReport report=report();when(accounts.requireActiveAdmin(1)).thenReturn(account(1,"ADMIN"));when(reports.findLockedById(100L)).thenReturn(Optional.of(report));when(events.request(report,1)).thenReturn("command-1");var view=governance.decide(new CurrentActor(1,"ADMIN"),100,new ContentGovernance.Decision(ReportStatus.RESOLVED,GovernanceAction.REMOVE_ITEM,"确认违规并下架"));assertThat(view.status()).isEqualTo(ReportStatus.RESOLVED);assertThat(view.actionState()).isEqualTo(ActionState.PENDING);assertThat(report.getActionEventId()).isEqualTo("command-1");verify(events).request(report,1);}
    @Test void dismissalNeverDispatchesRemoteAction(){ContentReport report=report();when(accounts.requireActiveAdmin(1)).thenReturn(account(1,"ADMIN"));when(reports.findLockedById(100L)).thenReturn(Optional.of(report));var view=governance.decide(new CurrentActor(1,"ADMIN"),100,new ContentGovernance.Decision(ReportStatus.DISMISSED,GovernanceAction.NONE,"核查后无需处理"));assertThat(view.actionState()).isEqualTo(ActionState.NONE);verifyNoInteractions(events);}
    @Test void staleActionResultCannotOverwriteLatestRetry(){ContentReport report=report();report.setStatus(ReportStatus.RESOLVED);report.setDecisionAction(GovernanceAction.REMOVE_ITEM);report.setActionState(ActionState.PENDING);report.setActionEventId("new-command");report.setHandledBy(1L);when(reports.findLockedById(100L)).thenReturn(Optional.of(report));when(inbox.existsById("old-result")).thenReturn(false);governance.applyActionResult(new ContentGovernance.ActionResult("old-result","old-command","GovernanceActionFailed",100,"late"));assertThat(report.getActionState()).isEqualTo(ActionState.PENDING);verify(actions,never()).save(any());}
    @Test void matchingAppliedResultCompletesDeliveryExactlyOnce(){ContentReport report=pendingReport("command-1");when(reports.findLockedById(100L)).thenReturn(Optional.of(report));when(inbox.existsById("result-1")).thenReturn(false,true);var first=governance.applyActionResult(new ContentGovernance.ActionResult("result-1","command-1","GovernanceActionApplied",100,null));var duplicate=governance.applyActionResult(new ContentGovernance.ActionResult("result-1","command-1","GovernanceActionApplied",100,null));assertThat(first.actionState()).isEqualTo(ActionState.APPLIED);assertThat(duplicate.actionState()).isEqualTo(ActionState.APPLIED);verify(actions,times(1)).save(any(ReportAction.class));verify(inbox,times(1)).saveAndFlush(any(GovernanceInboxEvent.class));}
    @Test void failedDeliveryCanRetryWithoutChangingDecision(){ContentReport report=pendingReport("command-1");when(reports.findLockedById(100L)).thenReturn(Optional.of(report));when(inbox.existsById("result-1")).thenReturn(false);governance.applyActionResult(new ContentGovernance.ActionResult("result-1","command-1","GovernanceActionFailed",100,"商品服务暂时不可用"));assertThat(report.getActionState()).isEqualTo(ActionState.FAILED);when(accounts.requireActiveAdmin(1)).thenReturn(account(1,"ADMIN"));when(events.request(report,1)).thenReturn("command-2");var retried=governance.decide(new CurrentActor(1,"ADMIN"),100,new ContentGovernance.Decision(ReportStatus.RESOLVED,GovernanceAction.REMOVE_ITEM,"重试原治理措施"));assertThat(retried.status()).isEqualTo(ReportStatus.RESOLVED);assertThat(retried.actionState()).isEqualTo(ActionState.PENDING);assertThat(report.getActionEventId()).isEqualTo("command-2");}
    private AccountGovernancePort.AccountSnapshot account(long id,String role){return new AccountGovernancePort.AccountSnapshot(id,"u"+id,role.equals("ADMIN")?"管理员":"学生","ACTIVE",role);}
    private ContentReport report(){ContentReport r=new ContentReport();r.setId(100L);r.setReporterId(2L);r.setReporterName("学生");r.setTargetType(ReportTargetType.ITEM);r.setTargetId(10L);r.setReportedUserId(7L);r.setTargetSummary("教材");r.setReasonCode(ReportReason.FRAUD);r.setDescription("这是足够详细的举报说明文字");r.setCreatedAt(LocalDateTime.now(clock));r.setUpdatedAt(LocalDateTime.now(clock));return r;}
    private ContentReport pendingReport(String eventId){ContentReport r=report();r.setStatus(ReportStatus.RESOLVED);r.setDecisionAction(GovernanceAction.REMOVE_ITEM);r.setActionState(ActionState.PENDING);r.setActionEventId(eventId);r.setHandledBy(1L);return r;}
}
