package com.campus.secondhand.governance;

import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.time.*;import java.util.*;import javax.crypto.spec.SecretKeySpec;
import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.http.MediaType;import org.springframework.security.oauth2.jose.jws.MacAlgorithm;import org.springframework.security.oauth2.jwt.*;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class GovernanceApiTest {
    private static final String SECRET="test-internal-jwt-secret-at-least-32-bytes";@Autowired MockMvc mvc;@MockitoBean ContentGovernance governance;
    @Test void protectedRoutesRejectAnonymous()throws Exception{mvc.perform(get("/api/reports/mine")).andExpect(status().isUnauthorized());mvc.perform(get("/api/admin/reports")).andExpect(status().isUnauthorized());}
    @Test void reporterIdentityComesOnlyFromGatewayJwt()throws Exception{when(governance.submit(any(),any())).thenReturn(view());mvc.perform(post("/api/reports").header("Authorization","Bearer "+jwt(2,"STUDENT")).contentType(MediaType.APPLICATION_JSON).content("{\"targetType\":\"ITEM\",\"targetId\":10,\"reasonCode\":\"FRAUD\",\"description\":\"这是足够详细的举报说明文字\",\"reporterId\":999}")).andExpect(status().isOk()).andExpect(jsonPath("$.data.reporterId").value(2));verify(governance).submit(argThat(actor->actor.userId()==2),any());}
    @Test void studentCannotUseAdminQueue()throws Exception{mvc.perform(get("/api/admin/reports").header("Authorization","Bearer "+jwt(2,"STUDENT"))).andExpect(status().isForbidden());}
    @Test void internalResultRequiresServiceToken()throws Exception{when(governance.applyActionResult(any())).thenReturn(view());String body="{\"eventId\":\"r1\",\"correlationId\":\"c1\",\"type\":\"GovernanceActionApplied\",\"reportId\":100}";mvc.perform(post("/internal/governance/action-results").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isUnauthorized());mvc.perform(post("/internal/governance/action-results").header("X-Internal-Service-Token","test-internal-service-token-32-bytes").contentType(MediaType.APPLICATION_JSON).content(body)).andExpect(status().isOk());}
    private ContentGovernance.ReportView view(){return new ContentGovernance.ReportView(100L,2L,"学生",ReportTargetType.ITEM,10L,7L,"教材",ReportReason.FRAUD,"这是足够详细的举报说明文字",ReportStatus.OPEN,GovernanceAction.NONE,ActionState.NONE,null,null,LocalDateTime.now(),null,List.of());}
    private String jwt(long user,String role){Instant now=Instant.now();JwtClaimsSet claims=JwtClaimsSet.builder().issuer("campus-gateway").subject(String.valueOf(user)).claim("role",role).issuedAt(now).expiresAt(now.plusSeconds(60)).build();JwtEncoder encoder=NimbusJwtEncoder.withSecretKey(new SecretKeySpec(SECRET.getBytes(java.nio.charset.StandardCharsets.UTF_8),"HmacSHA256")).build();return encoder.encode(JwtEncoderParameters.from(JwsHeader.with(MacAlgorithm.HS256).build(),claims)).getTokenValue();}
}
