package com.campus.secondhand.trading.chat;

import static org.assertj.core.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.campus.secondhand.trading.TradingException;import java.time.*;import java.util.*;import org.junit.jupiter.api.*;

class DirectChatServiceTest{
 private final ChatConversationRepository conversations=mock(ChatConversationRepository.class);private final ChatMessageRepository messages=mock(ChatMessageRepository.class);private final ChatBlockRepository blocks=mock(ChatBlockRepository.class);private final AccountPort accounts=mock(AccountPort.class);private final MarketplacePort marketplace=mock(MarketplacePort.class);private final OrderConversationPort orders=mock(OrderConversationPort.class);private final ConversationCreator creator=mock(ConversationCreator.class);private final Clock clock=Clock.fixed(Instant.parse("2026-08-28T02:00:00Z"),ZoneOffset.UTC);private DirectChatService chat;
 @BeforeEach void setup(){chat=new DirectChatService(conversations,messages,blocks,accounts,marketplace,orders,creator,clock);when(accounts.activeStudent(anyLong())).thenAnswer(call->Optional.of(account(call.getArgument(0))));}
 @Test void openItemConversationUsesOneStableConversation(){ChatConversation c=conversation();when(marketplace.item(10L)).thenReturn(Optional.of(new MarketplacePort.Item(10L,7L,"教材","/i.jpg",true)));when(conversations.findByItemIdAndBuyerIdAndSellerId(10L,2L,7L)).thenReturn(Optional.empty());when(creator.create(eq(10L),eq(2L),eq(7L),anyString(),anyString(),anyString(),any())).thenReturn(c);var view=chat.open(2L,10L);assertThat(view.otherUserId()).isEqualTo(7L);assertThat(view.itemTitle()).isEqualTo("教材");}
 @Test void sendAdvancesSequenceAndCreatesUnreadForCounterparty(){ChatConversation c=conversation();when(conversations.findLocked(c.getPublicId())).thenReturn(Optional.of(c));when(blocks.either(2L,7L)).thenReturn(false);when(messages.countBySenderIdAndCreatedAtAfter(eq(2L),any())).thenReturn(0L);chat.send(2L,c.getPublicId(),"你好");when(conversations.allForActor(7L)).thenReturn(List.of(c));assertThat(c.getNextSequence()).isEqualTo(2L);assertThat(chat.unreadTotal(7L)).isEqualTo(1);verify(messages).save(argThat(m->m.getSequenceNumber()==1L&&m.getSenderId()==2L));}
 @Test void eitherDirectionBlockStopsSending(){ChatConversation c=conversation();when(conversations.findLocked(c.getPublicId())).thenReturn(Optional.of(c));when(blocks.either(2L,7L)).thenReturn(true);assertThatThrownBy(()->chat.send(2L,c.getPublicId(),"你好")).isInstanceOf(TradingException.class).hasMessageContaining("无法");verify(messages,never()).save(any());}
 @Test void strangerCannotReadConversation(){ChatConversation c=conversation();when(conversations.findByPublicId(c.getPublicId())).thenReturn(Optional.of(c));assertThatThrownBy(()->chat.history(9L,c.getPublicId(),null,50)).isInstanceOf(TradingException.class).hasMessage("会话不存在");}
 private AccountPort.Account account(Long id){return new AccountPort.Account(id,id==2?"买家":"卖家","u"+id);}private ChatConversation conversation(){ChatConversation c=new ChatConversation();c.setItemId(10L);c.setBuyerId(2L);c.setSellerId(7L);c.setBuyerNickname("买家");c.setSellerNickname("卖家");c.setItemTitleSnapshot("教材");c.setItemImageSnapshot("/i.jpg");return c;}
}
