package com.campus.secondhand.marketplace;

import static org.assertj.core.api.Assertions.assertThat;import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import java.math.BigDecimal;import org.junit.jupiter.api.*;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.bean.override.mockito.MockitoBean;import org.springframework.test.web.servlet.MockMvc;

@SpringBootTest @AutoConfigureMockMvc @ActiveProfiles("test")
class MarketplaceTradingEventTest{
 @Autowired TradingEventHandler handler;@Autowired ItemRepository items;@Autowired MarketplaceInboxRepository inbox;@Autowired MarketplaceOutboxRepository outbox;@Autowired MockMvc mvc;@MockitoBean AccountPublicPort accounts;@MockitoBean TradingInquiryPort trading;
 @BeforeEach void clean(){outbox.deleteAll();inbox.deleteAll();items.deleteAll();}
 @Test void reservationAndReleaseAreIdempotentAndOrderScoped(){Item item=item();handler.handle("e1","ItemReservationRequested",item.getId(),100L);handler.handle("e1","ItemReservationRequested",item.getId(),100L);Item reserved=items.findById(item.getId()).orElseThrow();assertThat(reserved.getStatus()).isEqualTo(ItemStatus.RESERVED);assertThat(reserved.getReservedOrderId()).isEqualTo(100L);assertThat(outbox.count()).isEqualTo(1);handler.handle("e2","ItemReleaseRequested",item.getId(),999L);assertThat(items.findById(item.getId()).orElseThrow().getStatus()).isEqualTo(ItemStatus.RESERVED);handler.handle("e3","ItemReleaseRequested",item.getId(),100L);assertThat(items.findById(item.getId()).orElseThrow().getStatus()).isEqualTo(ItemStatus.ON_SALE);}
 @Test void aSecondOrderCannotTakeOverAnExistingReservation(){Item item=item();handler.handle("e1","ItemReservationRequested",item.getId(),100L);handler.handle("e2","ItemReservationRequested",item.getId(),200L);Item reserved=items.findById(item.getId()).orElseThrow();assertThat(reserved.getStatus()).isEqualTo(ItemStatus.RESERVED);assertThat(reserved.getReservedOrderId()).isEqualTo(100L);assertThat(outbox.findAll()).extracting(event->event.eventType).containsExactlyInAnyOrder("ItemReserved","ItemReservationRejected");}
 @Test void internalSnapshotRequiresSharedServiceToken()throws Exception{Item item=item();mvc.perform(get("/internal/items/"+item.getId()+"/trade-snapshot")).andExpect(status().isForbidden());mvc.perform(get("/internal/items/"+item.getId()+"/trade-snapshot").header("X-Internal-Service-Token","test-internal-token-012345678901234567")).andExpect(status().isOk()).andExpect(jsonPath("$.data.sellerId").value(7));}
 private Item item(){Item item=new Item();item.setTitle("教材");item.setCategory("教材");item.setPrice(new BigDecimal("20"));item.setRegion("学院路");item.setSellerId(7L);return items.saveAndFlush(item);}
}
