package com.campus.secondhand.trading.chat;
import com.campus.secondhand.trading.*;import jakarta.validation.Valid;import jakarta.validation.constraints.*;import java.util.Map;import org.springframework.security.core.Authentication;import org.springframework.web.bind.annotation.*;
@RestController @RequestMapping("/api/chat") class ChatController{private final DirectChat chat;private final CurrentActorService actors;ChatController(DirectChat chat,CurrentActorService actors){this.chat=chat;this.actors=actors;}private Long actor(Authentication a){return actors.require(a).userId();}
 @PostMapping("/conversations")ApiResponse<DirectChat.ConversationView>open(Authentication a,@Valid@RequestBody OpenRequest r){return ApiResponse.ok(chat.open(actor(a),r.itemId()));}@PostMapping("/order-conversations")ApiResponse<DirectChat.ConversationView>openTrade(Authentication a,@Valid@RequestBody OpenTradeRequest r){return ApiResponse.ok(chat.openTrade(actor(a),r.orderId()));}
 @GetMapping("/conversations")ApiResponse<DirectChat.ConversationPage>list(Authentication a,@RequestParam(defaultValue="0")int page,@RequestParam(defaultValue="30")int size){return ApiResponse.ok(chat.conversations(actor(a),page,size));}@GetMapping("/conversations/{id}/messages")ApiResponse<DirectChat.MessagePage>history(Authentication a,@PathVariable String id,@RequestParam(required=false)Long beforeSequence,@RequestParam(defaultValue="50")int size){return ApiResponse.ok(chat.history(actor(a),id,beforeSequence,size));}
 @PostMapping("/conversations/{id}/messages")ApiResponse<DirectChat.MessageView>send(Authentication a,@PathVariable String id,@Valid@RequestBody SendRequest r){return ApiResponse.ok(chat.send(actor(a),id,r.body()));}@PostMapping("/conversations/{id}/read")ApiResponse<DirectChat.ConversationView>read(Authentication a,@PathVariable String id,@Valid@RequestBody ReadRequest r){return ApiResponse.ok(chat.markRead(actor(a),id,r.throughSequence()));}
 @PutMapping("/blocks/{userId}")ApiResponse<Void>block(Authentication a,@PathVariable Long userId){chat.block(actor(a),userId);return ApiResponse.ok(null);}@DeleteMapping("/blocks/{userId}")ApiResponse<Void>unblock(Authentication a,@PathVariable Long userId){chat.unblock(actor(a),userId);return ApiResponse.ok(null);}@GetMapping("/unread-count")ApiResponse<Map<String,Long>>unread(Authentication a){return ApiResponse.ok(Map.of("count",chat.unreadTotal(actor(a))));}
 record OpenRequest(@NotNull Long itemId){}record OpenTradeRequest(@NotNull Long orderId){}record SendRequest(@NotBlank@Size(max=2000)String body){}record ReadRequest(@NotNull Long throughSequence){}
}
