package com.campus.secondhand.trading.chat;

import com.campus.secondhand.trading.TradingException;
import java.time.Clock;import java.time.LocalDateTime;import java.util.*;
import org.springframework.dao.DataIntegrityViolationException;import org.springframework.data.domain.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;

@Service
public class DirectChatService implements DirectChat{
 private static final int MAX_CONVERSATIONS=50,MAX_MESSAGES=100,SENDS_PER_MINUTE=30;
 private final ChatConversationRepository conversations;private final ChatMessageRepository messages;private final ChatBlockRepository blocks;private final AccountPort accounts;private final MarketplacePort marketplace;private final OrderConversationPort orders;private final ConversationCreator creator;private final Clock clock;
 public DirectChatService(ChatConversationRepository c,ChatMessageRepository m,ChatBlockRepository b,AccountPort a,MarketplacePort p,OrderConversationPort o,ConversationCreator creator,Clock clock){conversations=c;messages=m;blocks=b;accounts=a;marketplace=p;orders=o;this.creator=creator;this.clock=clock;}
 @Override public ConversationView open(Long actor,Long itemId){AccountPort.Account buyer=requireStudent(actor);MarketplacePort.Item item=marketplace.item(itemId).orElseThrow(()->TradingException.notFound("商品不存在"));if(actor.equals(item.sellerId()))throw TradingException.conflict("SELF_CHAT","不能和自己发起私聊");AccountPort.Account seller=requireStudent(item.sellerId());Optional<ChatConversation> existing=conversations.findByItemIdAndBuyerIdAndSellerId(itemId,buyer.id(),seller.id());if(existing.isPresent())return view(existing.get(),actor);if(!item.publicTradable())throw TradingException.conflict("ITEM_UNAVAILABLE","该商品当前不能发起私聊");return view(createOrRead(item.id(),buyer.id(),seller.id(),display(buyer),display(seller),item.title(),item.imageUrl()),actor);}
 @Override public ConversationView openTrade(Long actor,Long orderId){requireStudent(actor);OrderConversationPort.Participants p=orders.participants(orderId).orElseThrow(()->TradingException.notFound("交易记录不存在"));if(!actor.equals(p.buyerId())&&!actor.equals(p.sellerId()))throw TradingException.forbidden("当前不能打开这笔交易的私聊");requireStudent(p.buyerId());requireStudent(p.sellerId());return view(conversations.findByItemIdAndBuyerIdAndSellerId(p.itemId(),p.buyerId(),p.sellerId()).orElseGet(()->createOrRead(p.itemId(),p.buyerId(),p.sellerId(),p.buyerNickname(),p.sellerNickname(),p.itemTitle(),p.itemImageUrl())),actor);}
 private ChatConversation createOrRead(Long item,Long buyer,Long seller,String buyerName,String sellerName,String title,String image){try{return creator.create(item,buyer,seller,buyerName,sellerName,title,image);}catch(DataIntegrityViolationException conflict){return conversations.findByItemIdAndBuyerIdAndSellerId(item,buyer,seller).orElseThrow(()->conflict);}}
 @Override @Transactional(readOnly=true) public ConversationPage conversations(Long actor,int page,int size){requireStudent(actor);int safePage=Math.max(0,page),safeSize=Math.max(1,Math.min(size,MAX_CONVERSATIONS));Page<ChatConversation> found=conversations.forActor(actor,PageRequest.of(safePage,safeSize));return new ConversationPage(found.getContent().stream().map(c->view(c,actor)).toList(),safePage,safeSize,found.hasNext(),unreadUnchecked(actor));}
 @Override @Transactional(readOnly=true) public MessagePage history(Long actor,String id,Long before,int size){requireStudent(actor);ChatConversation c=participant(id,actor,false);int safeSize=Math.max(1,Math.min(size,MAX_MESSAGES));long cursor=before==null?Long.MAX_VALUE:Math.max(1,before);List<ChatMessage> found=new ArrayList<>(messages.page(c.getId(),cursor,PageRequest.of(0,safeSize+1)));boolean more=found.size()>safeSize;if(more)found.removeLast();Long next=more&&!found.isEmpty()?found.getLast().getSequenceNumber():null;Collections.reverse(found);return new MessagePage(view(c,actor),found.stream().map(this::viewMessage).toList(),next,more);}
 @Override @Transactional public MessageView send(Long actor,String id,String body){requireStudent(actor);String text=body==null?"":body.trim();if(text.isEmpty()||text.length()>2000)throw new IllegalArgumentException("消息内容应为 1 到 2000 个字符");ChatConversation c=participant(id,actor,true);Long other=other(c,actor);requireStudent(other);if(blocks.either(actor,other))throw TradingException.conflict("BLOCKED","当前无法向对方发送消息");if(messages.countBySenderIdAndCreatedAtAfter(actor,now().minusMinutes(1))>=SENDS_PER_MINUTE)throw new TradingException(org.springframework.http.HttpStatus.TOO_MANY_REQUESTS,"RATE_LIMITED","发送过于频繁，请稍后再试");long sequence=c.getNextSequence();ChatMessage m=new ChatMessage();m.setConversationId(c.getId());m.setSenderId(actor);m.setSequenceNumber(sequence);m.setBody(text);m.setCreatedAt(now());messages.save(m);c.setNextSequence(sequence+1);c.setLastMessageAt(m.getCreatedAt());c.setLastMessagePreview(text.length()<=160?text:text.substring(0,160));if(actor.equals(c.getBuyerId()))c.setBuyerLastReadSequence(sequence);else c.setSellerLastReadSequence(sequence);return viewMessage(m);}
 @Override @Transactional public ConversationView markRead(Long actor,String id,Long through){requireStudent(actor);ChatConversation c=participant(id,actor,true);long value=through==null?c.getNextSequence()-1:through;value=Math.max(0,Math.min(value,c.getNextSequence()-1));if(actor.equals(c.getBuyerId()))c.setBuyerLastReadSequence(Math.max(c.getBuyerLastReadSequence(),value));else c.setSellerLastReadSequence(Math.max(c.getSellerLastReadSequence(),value));return view(c,actor);}
 @Override @Transactional public void block(Long actor,Long other){requireStudent(actor);requireStudent(other);if(actor.equals(other))throw new IllegalArgumentException("不能屏蔽自己");if(!blocks.existsByBlockerIdAndBlockedId(actor,other)){ChatBlock b=new ChatBlock();b.setBlockerId(actor);b.setBlockedId(other);blocks.save(b);}}
 @Override @Transactional public void unblock(Long actor,Long other){requireStudent(actor);blocks.deleteByBlockerIdAndBlockedId(actor,other);}
 @Override @Transactional(readOnly=true) public long unreadTotal(Long actor){requireStudent(actor);return unreadUnchecked(actor);}
 private long unreadUnchecked(Long actor){return conversations.allForActor(actor).stream().mapToLong(c->unread(c,actor)).sum();}
 private ChatConversation participant(String id,Long actor,boolean locked){ChatConversation c=(locked?conversations.findLocked(id):conversations.findByPublicId(id)).orElseThrow(()->TradingException.notFound("会话不存在"));if(!actor.equals(c.getBuyerId())&&!actor.equals(c.getSellerId()))throw TradingException.notFound("会话不存在");return c;}
 private AccountPort.Account requireStudent(Long id){return accounts.activeStudent(id).orElseThrow(()->TradingException.forbidden("学生账号不可用"));}private String display(AccountPort.Account a){return a.nickname()==null||a.nickname().isBlank()?a.username():a.nickname();}private Long other(ChatConversation c,Long actor){return actor.equals(c.getBuyerId())?c.getSellerId():c.getBuyerId();}private long unread(ChatConversation c,Long actor){long read=actor.equals(c.getBuyerId())?c.getBuyerLastReadSequence():c.getSellerLastReadSequence();return Math.max(0,c.getNextSequence()-1-read);}private ConversationView view(ChatConversation c,Long actor){Long other=other(c,actor);String name=actor.equals(c.getBuyerId())?c.getSellerNickname():c.getBuyerNickname();boolean byMe=blocks.existsByBlockerIdAndBlockedId(actor,other);return new ConversationView(c.getPublicId(),c.getItemId(),c.getItemTitleSnapshot(),c.getItemImageSnapshot(),other,name,c.getLastMessagePreview(),c.getLastMessageAt(),c.getNextSequence()-1,unread(c,actor),byMe,blocks.either(actor,other));}private MessageView viewMessage(ChatMessage m){return new MessageView(m.getSequenceNumber(),m.getSenderId(),m.getBody(),m.getCreatedAt());}private LocalDateTime now(){return LocalDateTime.now(clock);}
}
