server:
  port: 8081
spring:
  application:
    name: campus-account-service
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
