apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campus-market
resources:
  - ../../base
  - mailpit.yaml
patches:
  - path: configmap-patch.yaml
secretGenerator:
  - name: campus-secrets
    envs:
      - .env.secret
generatorOptions:
  disableNameSuffixHash: true
