server:
    port: 8080
    servlet:
        context-path: /api

spring:
    application:
        name: campus-secondhand
    datasource:
        url: jdbc:mysql://localhost:3306/campus_secondhand?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
        username: root
        password: "051223"
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    mail:
        host: smtp.mailtrap.io
        port: 2525
        username: YOUR_MAILTRAP_USERNAME
        password: YOUR_MAILTRAP_PASSWORD
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

app:
    upload-dir: uploads
