apiVersion: v1
kind: ConfigMap
metadata:
  name: campus-config
data:
  ACCOUNT_SERVICE_URI: http://account-service:8081
  MARKETPLACE_SERVICE_URI: http://marketplace-service:8082
  TRADING_SERVICE_URI: http://trading-service:8083
  GOVERNANCE_SERVICE_URI: http://governance-service:8084
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
  RABBITMQ_USERNAME: campus
  CORS_ORIGINS: http://localhost:18080,http://127.0.0.1:18080
  SESSION_COOKIE_SECURE: "false"
  MAIL_ENABLED: "false"
  UPLOAD_DIR: /app/uploads
  GOVERNANCE_MESSAGING_ENABLED: "true"
  GOVERNANCE_EVENTS_ENABLED: "true"
  TRADING_MESSAGING_ENABLED: "true"
  TRADING_EVENTS_ENABLED: "true"
