apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: campus-market
resources:
  - namespace.yaml
  - configmap.yaml
  - pvc.yaml
  - mysql-statefulset.yaml
  - backend-deployment.yaml
  - web-deployment.yaml
